### ISSUE TITLE
Use REST API to manage courses

### ISSUE THREAD

**Issue by jadedsurfer** [startersacademy/fullstack-project-01#20]
As a course manager, I need to manage the course description and details so that the course offering can be included in the course catalog.

Acceptance Criteria:
-I can manage the following information about a course:
--title
--courseType (video, WBT, instructor led)
--description
--instructors
--students

-I can create a course
-I can view a course
-I can modify an existing course
-I can delete a course

**Comment by goldlilys** [comment]
Demo video for this is http://www.screencast.com/t/hyoPWI9wyfwR
