### ISSUE TITLE
Use REST API to manage accounts

### ISSUE THREAD

**Issue by jadedsurfer** [startersacademy/fullstack-project-01#24]
As a corporate account rep, I need to manage information about the account's I have so that I can determine who from their organization is entitled to participate in courses.

Acceptance Criteria:
-I can manage the following information about an account:
--name
--account type (enterprise, commercial, federal)
--students

-I can create an account
-I can view an account
-I can modify an existing account
-I can delete an account

**Comment by tbashor** [comment]
Screencast: http://www.screencast.com/t/wbV7trwGIy
