### ISSUE TITLE
View Home page

### ISSUE THREAD

**Issue by jadedsurfer** [startersacademy/fullstack-project-01#5]
Acceptance Criteria:
I can:
-Navigate to this page according to the site map url
-See that the page looks like the mockup
-View the page at different resolutions and the content is laid out logically

**Comment by jadedsurfer** [comment]
![home](https://cloud.githubusercontent.com/assets/9160941/5653372/7c4207e0-966e-11e4-8709-4bd76cc05542.png)

**Comment by tbashor** [comment]
Please put in the link to the demo video.
