### ISSUE TITLE
View About Us page

### ISSUE THREAD

**Issue by jadedsurfer** [startersacademy/fullstack-project-01#6]
Acceptance Criteria:
I can:
-Navigate to this page according to the site map url
-See that the page looks like the mockup
-View the page at different resolutions and the content is laid out logically

**Comment by jadedsurfer** [comment]
![aboutus](https://cloud.githubusercontent.com/assets/9160941/5653369/7398ccb4-966e-11e4-8306-9226f127d023.png)

**Comment by tbashor** [comment]
Please put in the link to the demo video.
