### ISSUE TITLE
View About the Courses page

### ISSUE THREAD

**Issue by jadedsurfer** [startersacademy/fullstack-project-01#8]
Acceptance Criteria:
I can:
-Navigate to this page according to the site map url
-See that the page looks like the mockup
-View the page at different resolutions and the content is laid out logically

**Comment by jadedsurfer** [comment]
![aboutcourses](https://cloud.githubusercontent.com/assets/9160941/5653360/6321f158-966e-11e4-884f-7f9b398e4524.png)

**Comment by goldlilys** [comment]
Video demo http://www.screencast.com/t/3dUP5xyN
